import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar/navBar";
import SideBar from "@/components/layout/SideBar/sideBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <div className="app-layout">
          <header>
            <NavBar />
          </header>
          <SideBar />
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
